import type { User } from './types';

export const USERS: User[] = [
  {
    id: 'u_sparkydave',
    handle: 'sparky_dave',
    display_name: 'Sparky Dave',
    trade: 'Electrician',
    suburb: 'Bowen Hills',
    avatar_color: '#FF7A00',
    initials: 'SD',
    bio: 'Sparky 14 yrs. Will travel 5km extra for a decent flat white.',
    joined: '2025-08-12',
    stats: { reviews: 47, helpful_marks: 312, venues_visited: 28, streak_days: 41 },
    badges: [
      { code: 'top_reviewer', label: 'Top Reviewer', color: '#FF7A00' },
      { code: 'early_bird', label: 'Early Bird', color: '#F2C200' },
      { code: 'gossoko_legend', label: 'Smoko Legend', color: '#A8E000' },
    ],
  },
  {
    id: 'u_bigsteve',
    handle: 'big_steve_chippy',
    display_name: 'Big Steve',
    trade: 'Carpenter',
    suburb: 'Newstead',
    avatar_color: '#A8E000',
    initials: 'BS',
    bio: 'Chippy. 6ft 4. Will rate any feed by whether it fits in a normal lunch box.',
    joined: '2025-09-03',
    stats: { reviews: 31, helpful_marks: 188, venues_visited: 19, streak_days: 12 },
    badges: [
      { code: 'feed_hunter', label: 'Feed Hunter', color: '#A8E000' },
      { code: 'verified', label: 'Verified Tradie', color: '#FF7A00' },
    ],
  },
  {
    id: 'u_rachel',
    handle: 'rachel_concrete',
    display_name: 'Rachel',
    trade: 'Concreter',
    suburb: 'Salisbury',
    avatar_color: '#FF5500',
    initials: 'RC',
    bio: 'Concrete crew lead. Bulk orders welcome.',
    joined: '2025-10-15',
    stats: { reviews: 22, helpful_marks: 96, venues_visited: 14, streak_days: 8 },
    badges: [
      { code: 'crew_lead', label: 'Crew Lead', color: '#FF5500' },
      { code: 'verified', label: 'Verified Tradie', color: '#FF7A00' },
    ],
  },
  {
    id: 'u_jimbo',
    handle: 'brickie_jimbo',
    display_name: 'Jimbo',
    trade: 'Bricklayer',
    suburb: 'Geebung',
    avatar_color: '#F2C200',
    initials: 'JB',
    bio: 'Brickie. Eat first, ask questions later.',
    joined: '2025-11-22',
    stats: { reviews: 18, helpful_marks: 64, venues_visited: 11, streak_days: 22 },
    badges: [
      { code: 'feed_hunter', label: 'Feed Hunter', color: '#A8E000' },
    ],
  },
  {
    id: 'u_kate',
    handle: 'plumber_kate',
    display_name: 'Plumber Kate',
    trade: 'Plumber',
    suburb: 'Coorparoo',
    avatar_color: '#FF9533',
    initials: 'PK',
    bio: 'Plumber, 10 yrs in commercial. Hidden-gem hunter.',
    joined: '2026-01-04',
    stats: { reviews: 26, helpful_marks: 143, venues_visited: 17, streak_days: 5 },
    badges: [
      { code: 'hidden_gem', label: 'Hidden Gem Finder', color: '#A8E000' },
      { code: 'verified', label: 'Verified Tradie', color: '#FF7A00' },
    ],
  },
  {
    id: 'u_tilers',
    handle: 'tilers_united',
    display_name: 'Tilers United',
    trade: 'Tiler',
    suburb: 'Eagle Farm',
    avatar_color: '#E63946',
    initials: 'TU',
    bio: 'Two-man tiling crew. We rate based on ute apron size.',
    joined: '2025-12-08',
    stats: { reviews: 14, helpful_marks: 51, venues_visited: 9, streak_days: 3 },
    badges: [],
  },
];

export const USER_BY_HANDLE = new Map(USERS.map((u) => [u.handle, u]));
export const CURRENT_USER = USERS[0];
