import type { Venue } from './types';

const avg = (r: Venue['ratings']) =>
  Math.round(
    ((r.coffee_strength + r.feed_size + r.bang_for_buck + r.speed + r.ute_parking + r.early_open + r.service) / 7) * 10,
  ) / 10;

const make = (v: Omit<Venue, 'overall'>): Venue => ({ ...v, overall: avg(v.ratings) });

export const VENUES: Venue[] = [
  make({
    id: 'v_smokostop',
    slug: 'the-smoko-stop',
    name: 'The Smoko Stop',
    venue_type: 'gossoko_van',
    tagline: 'Bowen Hills coffee van — chippies & sparkies welcome.',
    description: 'Mobile coffee van parked on Abbotsford Rd opposite the BCC depot. Espresso runs from 4:30am, bacon-and-egg rolls by 5. Cash + tap accepted, big trailer apron for ute parking.',
    suburb: 'Bowen Hills',
    address: 'Abbotsford Rd opp. depot',
    postcode: '4006',
    lat: -27.4470, lng: 153.0381,
    open_now: true, opens_at: '04:30', closes_at: '11:30',
    price_level: 2, verified: true, trending: true,
    distance_km: 1.2,
    ratings: { coffee_strength: 5, feed_size: 4, bang_for_buck: 5, speed: 5, ute_parking: 5, early_open: 5, service: 5 },
    review_count: 184,
    hero_color: '#1a1310', hero_accent: '#FF7A00',
    badges: ['top_rated', 'verified', 'early_open'],
    tags: ['Espresso', 'B&E Roll', 'Tap Pay'],
    signature: 'Double-shot flat white + B&E roll',
  }),
  make({
    id: 'v_crowbar',
    slug: 'crowbar-coffee',
    name: 'Crowbar Coffee',
    venue_type: 'cafe',
    tagline: 'Newstead café in a converted forge — strong coffee, no nonsense.',
    description: 'Industrial-fitout café with roller doors that open onto Doggett St. Beans from a Northgate roaster. Hot food bar from 6am, big lunch crowd from 11.',
    suburb: 'Newstead',
    address: '88 Doggett St',
    postcode: '4006',
    lat: -27.4500, lng: 153.0488,
    open_now: true, opens_at: '05:00', closes_at: '15:00',
    price_level: 2, verified: true, trending: false,
    distance_km: 2.1,
    ratings: { coffee_strength: 5, feed_size: 4, bang_for_buck: 4, speed: 4, ute_parking: 3, early_open: 5, service: 5 },
    review_count: 312,
    hero_color: '#181210', hero_accent: '#C1410D',
    badges: ['top_rated', 'verified'],
    tags: ['Single Origin', 'Hot Food', 'Indoor Seating'],
    signature: 'The "Sledge" — quad-shot long black',
  }),
  make({
    id: 'v_hardhat',
    slug: 'hard-hat-coffee-co',
    name: 'Hard Hat Coffee Co.',
    venue_type: 'gossoko_van',
    tagline: 'Rotating van — Eagle Farm Mon-Wed, Pinkenba Thu-Fri.',
    description: 'Custom-built coffee trailer that follows the big jobs. Posts location daily on socials. Bottomless filter for $4, espresso menu plus protein wraps.',
    suburb: 'Eagle Farm',
    address: 'Lomandra Pl (Mon–Wed)',
    postcode: '4009',
    lat: -27.4338, lng: 153.0850,
    open_now: true, opens_at: '04:00', closes_at: '11:00',
    price_level: 1, verified: true, trending: true,
    distance_km: 5.4,
    ratings: { coffee_strength: 4, feed_size: 4, bang_for_buck: 5, speed: 5, ute_parking: 5, early_open: 5, service: 4 },
    review_count: 96,
    hero_color: '#181410', hero_accent: '#FFB23A',
    badges: ['early_open', 'mobile'],
    tags: ['Filter Coffee', 'Wraps', 'Protein Bars'],
    signature: 'Bottomless filter + bacon wrap',
  }),
  make({
    id: 'v_bpbowen',
    slug: 'big-brekkie-bp-bowen',
    name: 'Big Brekkie BP Bowen',
    venue_type: 'servo',
    tagline: '24/7 servo with a proper hot bar — pies, snags, all-day brekkie.',
    description: 'Servo with an unusually serious kitchen — full English brekkie until 11am, $3 pies all day, dual coffee machines so the queue moves fast.',
    suburb: 'Bowen Hills',
    address: 'Bowen Bridge Rd',
    postcode: '4006',
    lat: -27.4434, lng: 153.0357,
    open_now: true, opens_at: '00:00', closes_at: '23:59',
    price_level: 1, verified: true, trending: false,
    distance_km: 1.6,
    ratings: { coffee_strength: 3, feed_size: 5, bang_for_buck: 5, speed: 4, ute_parking: 5, early_open: 5, service: 3 },
    review_count: 421,
    hero_color: '#161513', hero_accent: '#A8E000',
    badges: ['24_7', 'big_feed'],
    tags: ['24/7', 'Pies', 'Drive-thru Fuel'],
    signature: 'Big Brekkie box + double shot',
  }),
  make({
    id: 'v_uteparkcafe',
    slug: 'ute-park-cafe',
    name: 'Ute Park Café',
    venue_type: 'cafe',
    tagline: 'Hamilton café with the biggest ute apron in town.',
    description: 'Family-run café on Kingsford Smith Drive with a huge gravel lot — fits 20 utes plus trailers. Big breakfasts, good filter, friendly staff who remember your order.',
    suburb: 'Hamilton',
    address: '418 Kingsford Smith Dr',
    postcode: '4007',
    lat: -27.4400, lng: 153.0700,
    open_now: true, opens_at: '05:30', closes_at: '14:00',
    price_level: 2, verified: true, trending: false,
    distance_km: 4.0,
    ratings: { coffee_strength: 4, feed_size: 5, bang_for_buck: 4, speed: 3, ute_parking: 5, early_open: 4, service: 5 },
    review_count: 208,
    hero_color: '#171410', hero_accent: '#FF7A00',
    badges: ['ute_friendly', 'verified'],
    tags: ['Big Brekkie', 'Trailer Parking', 'Outdoor'],
    signature: 'The "Tradesman" — eggs, bacon, hash, snags',
  }),
  make({
    id: 'v_sitefeed',
    slug: 'site-feed-express',
    name: 'Site Feed Express',
    venue_type: 'food_truck',
    tagline: 'Hot food truck — does on-site catering runs by request.',
    description: 'Black-and-orange truck that posts up at the Eagle Farm racecourse car park Mon-Sat. Hot rolls, mince-and-cheese pies, decent coffee. Will deliver bulk orders to job sites within 5km.',
    suburb: 'Eagle Farm',
    address: 'Eagle Farm Racecourse car park',
    postcode: '4009',
    lat: -27.4338, lng: 153.0850,
    open_now: false, opens_at: '04:30', closes_at: '12:00',
    price_level: 2, verified: false, trending: true,
    distance_km: 5.6,
    ratings: { coffee_strength: 3, feed_size: 5, bang_for_buck: 4, speed: 5, ute_parking: 5, early_open: 5, service: 4 },
    review_count: 71,
    hero_color: '#171210', hero_accent: '#FF5500',
    badges: ['catering', 'mobile'],
    tags: ['Hot Rolls', 'Catering', 'Bulk Orders'],
    signature: 'Mince-and-cheese pie + sausage roll',
  }),
  make({
    id: 'v_concretecup',
    slug: 'concrete-cup',
    name: 'Concrete Cup',
    venue_type: 'gossoko_van',
    tagline: 'Northgate freight yard coffee van — runs out by 8am most days.',
    description: 'Tiny black caravan with a single barista who knows everyone. Cash only, but the line moves like clockwork. Open from 4am for the early shift.',
    suburb: 'Northgate',
    address: 'Toombul Rd freight gate',
    postcode: '4013',
    lat: -27.4012, lng: 153.0712,
    open_now: true, opens_at: '04:00', closes_at: '10:00',
    price_level: 1, verified: true, trending: false,
    distance_km: 7.1,
    ratings: { coffee_strength: 5, feed_size: 2, bang_for_buck: 5, speed: 5, ute_parking: 4, early_open: 5, service: 5 },
    review_count: 142,
    hero_color: '#181210', hero_accent: '#FFB23A',
    badges: ['cash_only', 'early_open'],
    tags: ['Cash Only', 'Espresso', 'Locals'],
    signature: 'Double ristretto + bacon and egg sanga',
  }),
  make({
    id: 'v_4ambakery',
    slug: 'the-4am-bakery',
    name: 'The 4am Bakery',
    venue_type: 'bakery',
    tagline: 'Stafford bakery — open before the sun, sold out by 9.',
    description: 'Hot bread out of the oven at 4am sharp. Hand-rolled pies, big sausage rolls, lamingtons. Cheap coffee, but you don\'t come here for the coffee.',
    suburb: 'Stafford',
    address: 'Stafford Rd',
    postcode: '4053',
    lat: -27.4030, lng: 153.0205,
    open_now: true, opens_at: '04:00', closes_at: '14:00',
    price_level: 1, verified: true, trending: false,
    distance_km: 8.2,
    ratings: { coffee_strength: 2, feed_size: 5, bang_for_buck: 5, speed: 4, ute_parking: 4, early_open: 5, service: 4 },
    review_count: 267,
    hero_color: '#191410', hero_accent: '#F2C200',
    badges: ['family_run', 'early_open'],
    tags: ['Pies', 'Fresh Bread', 'Lamingtons'],
    signature: 'Steak-and-mushroom pie',
  }),
  make({
    id: 'v_steelcap',
    slug: 'steel-cap-sammies',
    name: 'Steel Cap Sammies',
    venue_type: 'snack_bar',
    tagline: 'Geebung sandwich bar that builds the biggest rolls in Brisbane.',
    description: 'Counter-only sandwich shop. Order at the front, watch them build it. Choose-your-own meats, salads, sauces. Plates available if you want to dine in.',
    suburb: 'Geebung',
    address: '215 Newman Rd',
    postcode: '4034',
    lat: -27.3636, lng: 153.0625,
    open_now: true, opens_at: '05:00', closes_at: '14:30',
    price_level: 1, verified: false, trending: false,
    distance_km: 9.4,
    ratings: { coffee_strength: 2, feed_size: 5, bang_for_buck: 5, speed: 3, ute_parking: 5, early_open: 4, service: 5 },
    review_count: 158,
    hero_color: '#171411', hero_accent: '#A8E000',
    badges: ['big_feed', 'family_run'],
    tags: ['Sandwiches', 'Build-Your-Own', 'Cash + Tap'],
    signature: 'Triple-stack roast beef on white',
  }),
  make({
    id: 'v_diesel',
    slug: 'diesel-and-donuts',
    name: 'Diesel & Donuts',
    venue_type: 'food_truck',
    tagline: 'Salisbury food truck — diesel coffee, hot donuts, no nonsense.',
    description: 'Loud, fast, busy. Coffee strong enough to wake the dead, donuts fresh every hour. Truck-friendly with a big concrete pad.',
    suburb: 'Salisbury',
    address: 'Evans Rd industrial estate',
    postcode: '4107',
    lat: -27.5750, lng: 153.0381,
    open_now: true, opens_at: '04:30', closes_at: '13:00',
    price_level: 1, verified: false, trending: true,
    distance_km: 12.3,
    ratings: { coffee_strength: 5, feed_size: 3, bang_for_buck: 5, speed: 5, ute_parking: 5, early_open: 5, service: 3 },
    review_count: 88,
    hero_color: '#1a1310', hero_accent: '#FF5500',
    badges: ['mobile', 'big_feed'],
    tags: ['Donuts', 'Strong Coffee', 'Truck Lot'],
    signature: 'Hot cinnamon donut + diesel filter',
  }),
  make({
    id: 'v_spanner',
    slug: 'spanner-espresso',
    name: 'Spanner Espresso',
    venue_type: 'cafe',
    tagline: 'Woolloongabba café in an old mechanic\'s — bench seats from a Holden.',
    description: 'Beautifully fitted-out workshop conversion. Specialty coffee, brunch menu, a bit pricier but the service is sharp and the food slaps. Limited ute parking.',
    suburb: 'Woolloongabba',
    address: '94 Stanley St',
    postcode: '4102',
    lat: -27.4900, lng: 153.0350,
    open_now: true, opens_at: '05:30', closes_at: '14:00',
    price_level: 3, verified: true, trending: false,
    distance_km: 3.8,
    ratings: { coffee_strength: 5, feed_size: 4, bang_for_buck: 3, speed: 4, ute_parking: 2, early_open: 3, service: 5 },
    review_count: 244,
    hero_color: '#161311', hero_accent: '#FF9533',
    badges: ['top_rated', 'verified'],
    tags: ['Specialty', 'Brunch', 'Indoor'],
    signature: 'Bacon-jam toastie + flat white',
  }),
  make({
    id: 'v_sparkies',
    slug: 'sparkies-smoko',
    name: 'Sparkie\'s Smoko',
    venue_type: 'gossoko_van',
    tagline: 'Coorparoo van run by an ex-sparky. He gets it.',
    description: 'Old delivery van converted to a coffee rig. Started by Dave (ex-sparky) after he hung up the pliers. Mix of regulars from the industrial strip on Old Cleveland Rd.',
    suburb: 'Coorparoo',
    address: 'Old Cleveland Rd strip',
    postcode: '4151',
    lat: -27.4960, lng: 153.0676,
    open_now: true, opens_at: '05:00', closes_at: '11:00',
    price_level: 1, verified: true, trending: false,
    distance_km: 6.0,
    ratings: { coffee_strength: 4, feed_size: 3, bang_for_buck: 5, speed: 5, ute_parking: 4, early_open: 4, service: 5 },
    review_count: 117,
    hero_color: '#181311', hero_accent: '#FF7A00',
    badges: ['ex_trade', 'verified'],
    tags: ['Espresso', 'Snacks', 'Friendly'],
    signature: 'Long black + caramel slice',
  }),
  make({
    id: 'v_apprentice',
    slug: 'the-apprentices-lunch',
    name: 'The Apprentice\'s Lunch',
    venue_type: 'cafe',
    tagline: 'Bowen Hills cheap-eats café. Apprentice budget, foreman portions.',
    description: '$10 hot lunches Mon-Fri. Massive serves, basic décor, fast service. Cash discount of 5%. Owned by a former site manager who hated paying $25 for a sandwich.',
    suburb: 'Bowen Hills',
    address: '52 Brookes St',
    postcode: '4006',
    lat: -27.4458, lng: 153.0408,
    open_now: false, opens_at: '06:00', closes_at: '14:00',
    price_level: 1, verified: false, trending: true,
    distance_km: 1.4,
    ratings: { coffee_strength: 3, feed_size: 5, bang_for_buck: 5, speed: 4, ute_parking: 3, early_open: 3, service: 4 },
    review_count: 53,
    hero_color: '#191411', hero_accent: '#F2C200',
    badges: ['cheap_eats', 'big_feed'],
    tags: ['$10 Lunch', 'Cash Discount', 'Hot Meals'],
    signature: '$10 schnitty + chips + gravy',
  }),
  make({
    id: 'v_knockoff',
    slug: 'knock-off-kitchen',
    name: 'Knock-Off Kitchen',
    venue_type: 'restaurant',
    tagline: 'Capalaba post-shift feed — opens when the tools go down.',
    description: 'Started as a food truck, now a proper sit-down spot. Opens at 3pm Mon-Fri for the after-shift rush. Cold beer on tap, big meals, no fuss.',
    suburb: 'Capalaba',
    address: '101 Old Cleveland Rd',
    postcode: '4157',
    lat: -27.5279, lng: 153.1872,
    open_now: false, opens_at: '15:00', closes_at: '21:00',
    price_level: 2, verified: true, trending: false,
    distance_km: 18.7,
    ratings: { coffee_strength: 2, feed_size: 5, bang_for_buck: 4, speed: 3, ute_parking: 5, early_open: 1, service: 5 },
    review_count: 196,
    hero_color: '#181412', hero_accent: '#E63946',
    badges: ['after_hours', 'verified'],
    tags: ['Beer on Tap', 'Sit-Down', 'Late Open'],
    signature: 'Schnitty + jug of XXXX Gold',
  }),
  make({
    id: 'v_yatala',
    slug: 'yatala-tradies-co',
    name: 'Yatala Tradies Co.',
    venue_type: 'cafe_and_food_truck',
    tagline: 'Yatala dual setup — café inside, hot truck out front.',
    description: 'Equally good if you want to sit down or grab and go. Truck handles the early shift (4:30am), café opens at 6am for the longer feeds. Massive industrial estate clientele.',
    suburb: 'Yatala',
    address: 'Heron Place industrial estate',
    postcode: '4207',
    lat: -27.7460, lng: 153.2050,
    open_now: true, opens_at: '04:30', closes_at: '15:00',
    price_level: 2, verified: true, trending: true,
    distance_km: 38.4,
    ratings: { coffee_strength: 4, feed_size: 5, bang_for_buck: 4, speed: 5, ute_parking: 5, early_open: 5, service: 4 },
    review_count: 305,
    hero_color: '#171410', hero_accent: '#FF7A00',
    badges: ['top_rated', 'verified', 'big_feed'],
    tags: ['Dine-in + Take', 'Truck Lot', 'Bulk Orders'],
    signature: 'Big breakfast wrap + double-shot',
  }),
];

export const VENUE_BY_ID = new Map(VENUES.map((v) => [v.id, v]));
export const VENUE_BY_SLUG = new Map(VENUES.map((v) => [v.slug, v]));

export const TRENDING_VENUES = VENUES.filter((v) => v.trending);
export const OPEN_NOW_VENUES = VENUES.filter((v) => v.open_now);
export const TOP_RATED_VENUES = [...VENUES].sort((a, b) => b.overall - a.overall);
